import {apiUrl} from './lib/api';
import {useEffect,useState} from 'react';
import {Camera,Package,ShieldCheck,RefreshCw,Upload,Check,Plus,Eye} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';
import {groups,titles,photoTitles,emptyInventory,totalMerge,quantity,approximate,validateInventory,photoKinds,type Group,type Item,type Inventory,type PhotoKind} from '@/lib/inventory';
import {scanScreen,groupFor,regions} from '@/lib/screen-ocr';
type Row={nickname:string;details:Inventory;photos:Partial<Record<PhotoKind,string>>;updated_at:string};
const fmt=(n:number|null)=>n===null?'미입력':n.toLocaleString('ko-KR');
const amountText=(s:string)=>quantity(s)===null?'미입력':(approximate(s)?'약 ':'')+fmt(quantity(s));
function PhotoUpload({kind,file,existing,busy,onUpload}:{kind:PhotoKind;file?:File;existing?:string;busy:boolean;onUpload:(file:File,kind:PhotoKind)=>void}){
 const [url,setUrl]=useState('');useEffect(()=>{if(!file){setUrl(existing?apiUrl('/api/photos/'+existing):'');return;}const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file,existing]);
 return <div className="photo-slot"><label className={'upload '+(url?'has-photo':'')} htmlFor={'photo-'+kind}>{url?<><img src={url} alt={photoTitles[kind]}/><span className="replace"><Camera size={16}/> {photoTitles[kind]} 바꾸기</span></>:<><Upload size={24}/><strong>{photoTitles[kind]} 올리기</strong><span>사진에서 필요한 숫자만 읽어요</span><small>JPG · PNG · WEBP / 최대 5MB</small></>}</label><input className="sr-only" id={'photo-'+kind} type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f,kind);e.target.value='';}}/></div>;
}
function NumberField({label,value,onChange,unit=''}:{label:string;value:string;onChange:(s:string)=>void;unit?:string}){return <label className="number-field"><span>{label}{unit&&<small>{unit}</small>}</span><input inputMode="numeric" type="number" min="0" max="1000000000000" step="1" placeholder="미입력" value={value} onChange={e=>onChange(e.target.value)}/></label>;}
function Editor({group,item,patch,files,photos,busy,onUpload}:{group:Group;item:Item;patch:(key:keyof Item,value:string)=>void;files:Partial<Record<PhotoKind,File>>;photos:Partial<Record<PhotoKind,string>>;busy:boolean;onUpload:(f:File,k:PhotoKind)=>void}){
 const kind=group as PhotoKind;const mergeKind=(group+'Merge') as PhotoKind;
 return <><PhotoUpload kind={kind} file={files[kind]} existing={photos[kind]} busy={busy} onUpload={onUpload}/><label className="field-label">{group==='potion'?'녹색 물약 수량':'보유 소환 재화'}<input inputMode="decimal" placeholder="예: 35.8k 또는 35800" value={item.amount} onChange={e=>patch('amount',e.target.value)}/></label><p className="helper">{item.amount&&quantity(item.amount)!==null?`${amountText(item.amount)}개${approximate(item.amount)?' · 사진의 축약 표시를 그대로 저장합니다.':''}`:'사진에서 읽은 값은 등록 전에 확인해주세요.'}</p>
 {group!=='potion'&&<div className="level-fields"><NumberField label="소환 레벨" value={item.level} onChange={s=>patch('level',s)}/><NumberField label="현재 진행" value={item.progress} onChange={s=>patch('progress',s)}/><NumberField label="다음 레벨 목표" value={item.target} onChange={s=>patch('target',s)}/></div>}
 {(group==='egg'||group==='mount')&&<section className="merge-section"><h3>합성 수량</h3><PhotoUpload kind={mergeKind} file={files[mergeKind]} existing={photos[mergeKind]} busy={busy} onUpload={onUpload}/><div className="merge-fields"><NumberField label="사진 선택 수량" value={item.selected} onChange={s=>patch('selected',s)}/><NumberField label="추가 수량 (+α)" value={item.extra} onChange={s=>patch('extra',s)}/></div><p className="helper">사진의 ‘선택됨’ 숫자에 포함되지 않은 수량만 추가하세요.</p><div className="merge-total"><span>합성 합계</span><strong>{fmt(totalMerge(item))}<small>개</small></strong></div></section>}
 </>;
}
export default function Home(){
 const [records,setRecords]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [nickname,setNickname]=useState(''),[password,setPassword]=useState(''),[inventory,setInventory]=useState(emptyInventory);
 const [files,setFiles]=useState<Partial<Record<PhotoKind,File>>>({}),[photos,setPhotos]=useState<Partial<Record<PhotoKind,string>>>({});
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[saving,setSaving]=useState(false),[tab,setTab]=useState<Group>('skill'),[detail,setDetail]=useState<Row|null>(null);
 async function refresh(){setLoading(true);try{const r=await fetch(apiUrl('/api/records'),{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error);setRecords(d.records.map((r:Row)=>({...r,details:{...emptyInventory(),...r.details}})));setError('');}catch(e){setError(e instanceof Error?e.message:'현황을 불러오지 못했습니다.');}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_clan_resources',description:'클랜원이 등록한 재화·소환 레벨·합성 수량을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(){const r=await fetch(apiUrl('/api/records'));if(!r.ok)throw Error('현황 조회 실패');return await r.json();}},{signal:lifecycle.signal})).catch(console.error);return()=>lifecycle.abort();},[]);
 function patch(g:Group,key:keyof Item,value:string){setInventory(v=>({...v,[g]:{...v[g],[key]:value}}));}
 async function upload(file:File,kind:PhotoKind){
 setError('');setNotice('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('사진은 JPG, PNG, WEBP로 5MB 이하로 올려주세요.');return;}
 setFiles(v=>({...v,[kind]:file}));setBusy(true);setProgress(0);const g=groupFor(kind);
 setInventory(v=>{const next={...v[g]};for(const r of regions[kind])if(r.field==='ratio'){next.progress='';next.target='';}else next[r.field]='';return {...v,[g]:next};});
 try{const {item}=await scanScreen(file,kind,setProgress);setInventory(v=>({...v,[g]:{...v[g],...item}}));setNotice(Object.keys(item).length?`${photoTitles[kind]}를 읽었습니다. 수량과 레벨을 사진과 비교해주세요.`:'숫자를 읽지 못했습니다. 사진을 보며 직접 입력해주세요.');}catch(e){console.error(e);setError('사진 인식에 실패했습니다. 올린 사진은 유지되며 직접 입력할 수 있습니다.');}finally{setBusy(false);}
 }
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setNotice('');try{validateInventory(inventory);}catch(e){setError(e instanceof Error?e.message:'입력값을 확인해주세요.');return;}setSaving(true);try{const form=new FormData();form.set('nickname',nickname);form.set('password',password);form.set('inventory',JSON.stringify(inventory));for(const kind of photoKinds)if(files[kind])form.set('photo_'+kind,files[kind]!);const r=await fetch(apiUrl('/api/records'),{method:'POST',body:form});const d:any=await r.json();if(!r.ok)throw Error(d.error);await refresh();setNotice(`${nickname}님의 재화를 저장했습니다.`);setPassword('');}catch(e){setError(e instanceof Error?e.message:'저장 실패');}finally{setSaving(false);}}
 function edit(row:Row){setNickname(row.nickname);setInventory(structuredClone(row.details));setPhotos(row.photos);setFiles({});setPassword('');setDetail(null);setNotice('수정 비밀번호를 입력한 뒤 변경한 내용을 등록해주세요.');document.getElementById('registration')?.scrollIntoView({behavior:'smooth'});}
 const totals=groups.map(g=>records.reduce((sum,r)=>sum+(quantity(r.details[g].amount)||0),0));
 return <main><header className="topbar"><a className="brand" href={import.meta.env.BASE_URL}><span className="brand-icon"><Package size={23}/></span><span>클랜 재화관리 <small>포지마스터</small></span></a><span className="clan-badge"><ShieldCheck size={15}/> 우리 클랜</span></header><div className="workspace">
 <section className="page-heading"><div><p className="eyebrow">CLAN INVENTORY</p><h1>함께 모으는 재화 현황</h1><p>사진을 올리고 확인한 수량을 공유하세요.</p></div><button className="quiet" onClick={refresh} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>현황 새로고침</button></section>
 <div className="summary">{groups.map((g,i)=><article key={g}><span className={'resource-marker marker-'+i}>{['S','E','M','P'][i]}</span><div><p>{titles[g]} {g==='potion'?'':'소환 '}재화</p><strong>{records.some(r=>approximate(r.details[g].amount))&&<span className="approx">약 </span>}{fmt(totals[i])}<small>개</small></strong><span className="meta">{records.filter(r=>r.details[g].amount!=='').length}명 입력</span></div></article>)}</div>
 <div className="merge-summary"><span>알 합성 <strong>{fmt(records.reduce((s,r)=>s+(totalMerge(r.details.egg)||0),0))}개</strong></span><span>탈것 합성 <strong>{fmt(records.reduce((s,r)=>s+(totalMerge(r.details.mount)||0),0))}개</strong></span><span>등록한 클랜원 <strong>{records.length}명</strong></span></div>
 <div className="columns"><section className="panel registration" id="registration"><div className="panel-heading"><div><span className="eyebrow">MY RESOURCES</span><h2>내 재화 등록</h2></div><span className="step-badge">사진 · 확인 · 등록</span></div><form onSubmit={save}><label className="field-label" htmlFor="nickname">게임 닉네임</label><input id="nickname" required maxLength={24} placeholder="게임에서 사용하는 닉네임" value={nickname} onChange={e=>setNickname(e.target.value)}/>
 <fieldset disabled={busy||saving} className="editor-fieldset"><Tabs value={tab} onValueChange={v=>setTab(v as Group)}><TabsList className="resource-tabs">{groups.map(g=><TabsTrigger key={g} value={g}>{g==='potion'?'물약':g==='egg'?'알':titles[g]}</TabsTrigger>)}</TabsList>{groups.map(g=><TabsContent key={g} value={g}><Editor group={g} item={inventory[g]} patch={(k,s)=>patch(g,k,s)} files={files} photos={photos} busy={busy||saving} onUpload={upload}/></TabsContent>)}</Tabs></fieldset>
 {busy&&<div className="scan-status" role="status"><span>사진에서 숫자를 읽고 있습니다… {progress}%</span><Progress value={progress}/></div>}
 <label className="field-label" htmlFor="password">본인 수정 비밀번호</label><input id="password" type="password" minLength={6} maxLength={100} required autoComplete="off" placeholder="6자 이상 · 다음 수정 때도 사용" value={password} onChange={e=>setPassword(e.target.value)}/><p className="helper">처음 정한 비밀번호로 같은 닉네임의 재화를 수정합니다.</p>
 <button className="submit" type="submit" disabled={busy||saving}>{saving?'저장 중…':<><Check size={18}/>확인한 재화 등록</>}</button><p className="helper center">입력한 모든 항목이 함께 저장됩니다. 빈칸은 미입력입니다.</p></form></section>
 <section className="panel roster"><div className="panel-heading"><div><span className="eyebrow">CLAN OVERVIEW</span><h2>클랜원 재화 <span className="count">{records.length}</span></h2></div><span className="meta">최근 등록순</span></div>
 {loading&&records.length===0?<div className="empty">현황을 불러오고 있습니다.</div>:records.length===0?<div className="empty"><span className="empty-icon"><Package size={35}/></span><h3>첫 재화를 등록해주세요</h3><p>클랜원이 올린 최신 수량이<br/>이곳에 모이고 합계에 반영됩니다.</p></div>:<Table><TableHeader><TableRow><TableHead>닉네임 / 등록일</TableHead><TableHead className="number">스킬</TableHead><TableHead className="number">알 재화 / 합성</TableHead><TableHead className="number">탈것 재화 / 합성</TableHead><TableHead className="number">물약</TableHead></TableRow></TableHeader><TableBody>{records.map(row=><TableRow key={row.nickname}><TableCell><button className="nickname" onClick={()=>setDetail(row)}>{row.nickname}</button><span className="date">{new Date(row.updated_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</span></TableCell>{groups.map(g=><TableCell key={g} className="number">{amountText(row.details[g].amount)}{(g==='egg'||g==='mount')&&<span className="date">합성 {fmt(totalMerge(row.details[g]))}</span>}</TableCell>)}</TableRow>)}</TableBody></Table>}
 <div className="roster-note"><ShieldCheck size={18}/><p>닉네임을 누르면 소환 레벨·진행도·합성 내역과 사진을 볼 수 있어요.<br/>k로 표시된 수량과 그 합계는 ‘약’으로 표시합니다.</p></div></section></div>
 {error&&<div className="message error" role="alert">{error}</div>}{notice&&<div className="message success" role="status">{notice}</div>}
 <footer>FORGE MASTER <span>우리 클랜 재화 현황</span></footer></div>
 <Sheet open={!!detail} onOpenChange={open=>{if(!open)setDetail(null);}}><SheetContent className="detail-sheet overflow-y-auto"><SheetHeader><SheetTitle>{detail?.nickname}님의 재화</SheetTitle><SheetDescription>개인별 최신 등록 현황</SheetDescription></SheetHeader>{detail&&<div className="detail-body">{groups.map(g=><section className="detail-group" key={g}><h3>{titles[g]}</h3><dl><div><dt>보유 재화</dt><dd>{amountText(detail.details[g].amount)}{detail.details[g].amount&&<small>원래 표시: {detail.details[g].amount}</small>}</dd></div>{g!=='potion'&&<><div><dt>소환 레벨</dt><dd>{detail.details[g].level||'미입력'}</dd></div><div><dt>진행도</dt><dd>{detail.details[g].progress||'미입력'} / {detail.details[g].target||'미입력'}</dd></div></>}{(g==='egg'||g==='mount')&&<div><dt>합성 수량</dt><dd>{fmt(totalMerge(detail.details[g]))}<small>사진 {detail.details[g].selected||'미입력'} + 추가 {detail.details[g].extra||'0'}</small></dd></div>}</dl></section>)}<div className="evidence-links">{photoKinds.filter(k=>detail.photos[k]).map(k=><a key={k} href={apiUrl('/api/photos/'+detail.photos[k])} target="_blank" rel="noopener noreferrer"><Eye size={15}/>{photoTitles[k]}</a>)}</div><button className="submit" onClick={()=>edit(detail)}>내 재화 수정하기</button></div>}</SheetContent></Sheet>
 </main>;
}
