import ScanDiagnostics from './ScanDiagnostics';
import {ScanFailure,scanVersion,type ScanReport} from './lib/scan-diagnostics';
import {useEffect,useState} from 'react';
import {scanScreen} from './lib/screen-ocr';
import {photoKinds,photoTitles,type PhotoKind,type Item} from './lib/inventory';
import {imageFromTransfer,readScreenshot,normalizePhoto,maximumPhotoBytes} from './lib/photo-input';
export default function OcrCheck(){
 const [kind,setKind]=useState<PhotoKind>('egg'),[file,setFile]=useState<File>(),[busy,setBusy]=useState(false),[reading,setReading]=useState(false),[preview,setPreview]=useState(''),[progress,setProgress]=useState(0),[result,setResult]=useState<{item:Partial<Item>;original:string[]}>(),[error,setError]=useState(''),[diagnostics,setDiagnostics]=useState<ScanReport>();
 function selectPhoto(f:File){const normalized=normalizePhoto(f);setResult(undefined);setDiagnostics(undefined);setFile(undefined);if(!normalized||f.size>maximumPhotoBytes){setError('IMG-02 · 10MB 이하 JPG, PNG, WEBP 사진을 선택해주세요.');return;}setFile(normalized);setError('');}
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 useEffect(()=>{function paste(e:ClipboardEvent){if(busy||reading||!e.clipboardData)return;const target=e.target as HTMLElement|null;if(target?.closest('textarea,input:not([type="file"]),[contenteditable="true"]'))return;const image=imageFromTransfer(e.clipboardData);if(!image)return;e.preventDefault();selectPhoto(image);}window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste);},[busy,reading]);
 async function run(fresh=false){if(!file||busy)return;setBusy(true);setError('');setResult(undefined);setDiagnostics(undefined);setProgress(0);try{const result=await scanScreen(file,kind,setProgress,fresh);setResult(result);setDiagnostics(result.diagnostics);}catch(e){if(e instanceof ScanFailure)setDiagnostics(e.report);setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <main><div className="workspace" style={{maxWidth:650}}><section className="panel registration"><div className="panel-heading"><h1>사진 인식 점검</h1><small>점검 버전 {scanVersion}</small></div><div style={{padding:24}}><p>사진은 브라우저에서만 읽으며 재화 현황에 저장하지 않습니다.</p><label className="field-label">사진 종류<select value={kind} disabled={busy} onChange={e=>{setKind(e.target.value as PhotoKind);setResult(undefined);setDiagnostics(undefined);setError('');}}>{photoKinds.map(k=><option key={k} value={k}>{photoTitles[k]}</option>)}</select></label><div className="photo-slot" tabIndex={0} aria-label="점검 캡처 붙여넣기" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect=busy||reading?'none':'copy';}} onDrop={e=>{e.preventDefault();if(busy||reading)return;const image=imageFromTransfer(e.dataTransfer);if(image)selectPhoto(image);else setError('JPG, PNG, WEBP 캡처 파일을 놓아주세요.');}}><label className="field-label">원본 캡처 선택<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||reading} onChange={e=>{const f=e.target.files?.[0];if(f)selectPhoto(f);e.target.value='';}}/></label><button type="button" className="capture-paste" disabled={busy||reading} onClick={async()=>{setReading(true);setError('');try{selectPhoto(await readScreenshot());}catch(e){setError(e instanceof Error?e.message:'캡처를 붙여넣지 못했습니다.');}finally{setReading(false);}}}>{reading?'캡처 확인 중…':'복사한 캡처 붙여넣기'}</button><p className="helper">화면을 클릭하고 Ctrl+V로 캡처를 붙여넣거나 파일을 끌어놓으세요. 사진을 확인한 뒤 일반 인식 검사를 누르면 됩니다.</p>{preview&&<img src={preview} alt="검사할 캡처 미리보기" style={{maxWidth:'100%',maxHeight:240,objectFit:'contain'}}/>}<p role="status">{file?.name||'사진을 선택하거나 붙여넣어주세요.'}</p></div><button className="submit" disabled={!file||busy||reading} onClick={()=>run()}>일반 인식 검사</button><button className="capture-paste" disabled={!file||busy||reading} onClick={()=>run(true)}>호환 인식 검사</button>{busy&&<p role="status">인식 중 {progress}%</p>}{error&&<p role="alert">오류: {error}</p>}{diagnostics&&<ScanDiagnostics key={JSON.stringify(diagnostics)} report={diagnostics}/>} {result&&<div role="status"><h2>인식 결과</h2><dl>{(['amount','level','progress','target','selected'] as const).map(key=><div key={key}><dt>{{amount:'보유 수량',level:'소환 레벨',progress:'현재 단계',target:'진행 기준',selected:'합성 수량'}[key]}</dt><dd>{result.item[key]??'미인식'}</dd></div>)}</dl><h3>실제로 읽힌 문자</h3><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(result.original,null,2)}</pre></div>}<p><a href={import.meta.env.BASE_URL}>재화관리로 돌아가기</a></p></div></section></div></main>;
}
