import {useState} from 'react';
import {scanScreen} from './lib/screen-ocr';
import {photoKinds,photoTitles,type PhotoKind,type Item} from './lib/inventory';
import {normalizePhoto,maximumPhotoBytes} from './lib/photo-input';
export default function OcrCheck(){
 const [kind,setKind]=useState<PhotoKind>('egg'),[file,setFile]=useState<File>(),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[result,setResult]=useState<{item:Partial<Item>;original:string[]}>(),[error,setError]=useState('');
 async function run(fresh=false){if(!file||busy)return;setBusy(true);setError('');setResult(undefined);setProgress(0);try{setResult(await scanScreen(file,kind,setProgress,fresh));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <main><div className="workspace" style={{maxWidth:650}}><section className="panel registration"><div className="panel-heading"><h1>사진 인식 점검</h1><small>점검 버전 2026-10-02.2</small></div><div style={{padding:24}}><p>사진은 브라우저에서만 읽으며 재화 현황에 저장하지 않습니다.</p><label className="field-label">사진 종류<select value={kind} disabled={busy} onChange={e=>{setKind(e.target.value as PhotoKind);setResult(undefined);}}>{photoKinds.map(k=><option key={k} value={k}>{photoTitles[k]}</option>)}</select></label><label className="field-label">원본 캡처 선택<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(!f)return;const normalized=normalizePhoto(f);setResult(undefined);if(!normalized||f.size>maximumPhotoBytes){setError('10MB 이하 JPG, PNG, WEBP 사진을 선택해주세요.');return;}setFile(normalized);setError('');}}/></label><p>{file?.name||'사진을 선택해주세요.'}</p><button className="submit" disabled={!file||busy} onClick={()=>run()}>일반 인식 검사</button><button className="capture-paste" disabled={!file||busy} onClick={()=>run(true)}>호환 인식 검사</button>{busy&&<p role="status">인식 중 {progress}%</p>}{error&&<p role="alert">오류: {error}</p>}{result&&<div role="status"><h2>인식 결과</h2><dl>{(['amount','level','progress','target','selected'] as const).map(key=><div key={key}><dt>{{amount:'보유 수량',level:'소환 레벨',progress:'현재 단계',target:'진행 기준',selected:'합성 수량'}[key]}</dt><dd>{result.item[key]??'미인식'}</dd></div>)}</dl><h3>실제로 읽힌 문자</h3><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(result.original,null,2)}</pre></div>}<p><a href={import.meta.env.BASE_URL}>재화관리로 돌아가기</a></p></div></section></div></main>;
}
